deployment:
  version: 2
  tasks:
    - deploy:
        user: ameoconbantuongt
        group: ameoconbantuongt
        dir: public_html
        repository: https://github.com/Mink2k4/CodeMCBTT.git
        branch: main